package Rental;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AL-HACK3R
 */
import Connection.koneksilogin;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class rentcarView extends javax.swing.JFrame {

    Connection con;
    Statement stm;
    ResultSet rs;
    DefaultTableModel tabModel;
    String tanggal1, tanggal2;

    /**
     * Creates new form rentcarView
     */
    public rentcarView() {
        initComponents();
        setTitle("Form Peminjaman Mobil");
        merkField.setText("");
        typeField.setText("");
        tahunField.setText("");
        priceField.setText("");
        statusField.setText("");
        durasiField.setText("");
        totalField.setText("");
        tampil_data();
        tampil_combo();
    }

    private void tampil_combo() {
        try {
            con = koneksilogin.ConnectDB();
            String status = "Tersedia";
            String nopo = "select nopol from addcar where status = '"+status+"'";
            stm = con.createStatement();
            rs = stm.executeQuery(nopo);
            while (rs.next()) {
                String nopol = rs.getString(1);
                nopolCmb.addItem(nopol);
            }
        } catch (SQLException e) {

        }

    }

    public void tampil() {
        try {
            con = koneksilogin.ConnectDB();
            String no = "select * from addcar where nopol = '" + nopolCmb.getSelectedItem() + "'";
            stm = con.createStatement();
            rs = stm.executeQuery(no);
            while (rs.next()) {
                String merek = rs.getString("merek");
                String type = rs.getString("type");
                String tahun = rs.getString("tahun");
                String harga = rs.getString("harga");
                String check = rs.getString("status");
                
                merkField.setText(merek);
                typeField.setText(type);
                tahunField.setText(tahun);
                priceField.setText(harga);
                statusField.setText(check);
            }
        } catch (SQLException e) {

        }
    }
    
    private void clear() {
        merkField.setText("");
        typeField.setText("");
        tahunField.setText("");
        nopolCmb.setSelectedIndex(0);
        priceField.setText("");
        statusField.setText("");
        namaField.setText("");
        nikField.setText("");
        alamatField.setText("");
        teleponField.setText("");
        emailField.setText("");
        tgl1.setDate(null);
        tgl2.setDate(null);
        durasiField.setText("");
        totalField.setText("");
    }

    private void tampil_data() {
        Object baris[] = {"Id", "Merek Mobil", "Tipe Mobil", "Tahun Produksi", "No. Polisi", "Harga Sewa", "Status"};
        tabModel = new DefaultTableModel(null, baris);
        table.setModel(tabModel);
        try {
            con = new koneksilogin().ConnectDB();
            String select = "select * from addcar order by id ASC";
            stm = con.createStatement();
            rs = stm.executeQuery(select);
            while(rs.next()) {
                String id = rs.getString("id");
                String merek = rs.getString("merek");
                String type = rs.getString("type");
                String tahun = rs.getString("tahun");
                String nopol = rs.getString("nopol");
                String harga = rs.getString("harga");
                String status = rs.getString("status");
                String[] data = {id, merek, type, tahun, nopol, harga, status};
                tabModel.addRow(data);
            }
        }catch(SQLException e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        nikField = new javax.swing.JTextField();
        teleponField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatField = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        submitBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        nopolCmb = new javax.swing.JComboBox();
        tgl1 = new com.toedter.calendar.JDateChooser();
        tgl2 = new com.toedter.calendar.JDateChooser();
        hitungBtn = new javax.swing.JButton();
        typeField = new javax.swing.JLabel();
        merkField = new javax.swing.JLabel();
        tahunField = new javax.swing.JLabel();
        priceField = new javax.swing.JLabel();
        statusField = new javax.swing.JLabel();
        durasiField = new javax.swing.JLabel();
        rpField = new javax.swing.JLabel();
        totalField = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        refreshBtn1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 40, 64));
        jLabel1.setText("FORM PEMINJAMAN MOBIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Nama ");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("NIK");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("No. Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("E-mail");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        namaField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        namaField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(namaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 230, -1));

        nikField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nikField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(nikField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 230, -1));

        teleponField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        teleponField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(teleponField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, -1));

        emailField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 230, -1));

        alamatField.setColumns(20);
        alamatField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        alamatField.setRows(5);
        alamatField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(alamatField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 230, 87));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Merek Mobil");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Type Mobil");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Tahun Produksi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Harga Sewa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("No. Polisi");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Status");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Tanggal Peminjaman");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Tanggal Pengembalian");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("Lama peminjaman");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        table.setEnabled(false);
        jScrollPane5.setViewportView(table);
        new javax.swing.JTable()
        {};

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 1290, 230));

        submitBtn.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/enter (1).png"))); // NOI18N
        submitBtn.setText(" SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 190, -1));

        refreshBtn.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh (1).png"))); // NOI18N
        refreshBtn.setText(" REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        getContentPane().add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        nopolCmb.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nopolCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih No.Polisi" }));
        nopolCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolCmbActionPerformed(evt);
            }
        });
        getContentPane().add(nopolCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 180, -1));

        tgl1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tgl1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl1PropertyChange(evt);
            }
        });
        getContentPane().add(tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, 170, -1));

        tgl2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tgl2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl2PropertyChange(evt);
            }
        });
        getContentPane().add(tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 170, 170, -1));

        hitungBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hitungBtn.setText("HITUNG BIAYA");
        hitungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hitungBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 260, 200, -1));

        typeField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        typeField.setForeground(java.awt.Color.white);
        typeField.setText("jLabel16");
        getContentPane().add(typeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        merkField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        merkField.setForeground(java.awt.Color.white);
        merkField.setText("jLabel16");
        getContentPane().add(merkField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, -1, -1));

        tahunField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tahunField.setForeground(java.awt.Color.white);
        tahunField.setText("jLabel16");
        getContentPane().add(tahunField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, -1, -1));

        priceField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        priceField.setForeground(java.awt.Color.white);
        priceField.setText("jLabel16");
        getContentPane().add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        statusField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        statusField.setForeground(java.awt.Color.white);
        statusField.setText("jLabel16");
        getContentPane().add(statusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, -1, -1));

        durasiField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        durasiField.setForeground(java.awt.Color.white);
        durasiField.setText("jLabel16");
        getContentPane().add(durasiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 210, -1, -1));

        rpField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        rpField.setForeground(java.awt.Color.red);
        rpField.setText("Rp.");
        getContentPane().add(rpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 320, 110, -1));

        totalField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        totalField.setForeground(java.awt.Color.red);
        totalField.setText("jLabel16");
        getContentPane().add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1023, 320, 150, -1));

        clearBtn.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh.png"))); // NOI18N
        clearBtn.setText(" CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 200, -1));

        refreshBtn1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        refreshBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit.png"))); // NOI18N
        refreshBtn1.setText(" CLOSE");
        refreshBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(refreshBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 200, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/RENTAL MOBIL.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -340, -1, 1440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String nama = namaField.getText();
        long nik = Long.parseLong(nikField.getText());
        String alamat = alamatField.getText();
        long telepon = Long.parseLong(teleponField.getText());
        String email = emailField.getText();
        String nopol = nopolCmb.getSelectedItem().toString();
        long harga = Long.parseLong(priceField.getText());
        int durasi = Integer.parseInt(durasiField.getText());
        long total = Long.parseLong(totalField.getText()); 
        String tgll1 = tanggal1;
        String tgll2 = tanggal2;
        int doHapus = JOptionPane.showConfirmDialog(null, (Object) "Apakah data yang anda masukkan sudah benar?", "Cek Form", 0);
        if (doHapus == 0) {
            try {
                con = new koneksilogin().ConnectDB();
                String addRent = "INSERT INTO `addrent` (id, nama, nik, alamat, telpon, email, nopol, tgl_pinjam, tgl_kembali, harga, durasi, total) VALUES" + "(null, '"+nama+"','"+nik+"','"+alamat+"','"+telepon+"','"+email+"','"+nopol+"','"+tgll1+"','"+tgll2+"','"+harga+"', '"+durasi+"','"+total+"')";                
                stm = con.createStatement();
                stm.executeUpdate(addRent);
                tampil_data();
                JOptionPane.showMessageDialog(null, "Berhasil Menambah Data Peminjaman");
                try {
                    String status = "Tidak Tersedia";
                    String update = "update addcar set status = '"+status+"' where nopol = '"+nopolCmb.getSelectedItem().toString()+"'";
                    stm = con.createStatement();
                    stm.execute(update);
                    tampil_data();
                    clear();
                    tampil_combo();
                    try {
                        String addTransaction = "INSERT INTO `transaction` (id, nama, nik, alamat, telpon, email, nopol, tgl_pinjaman, tgl_kembali, harga, durasi, total) VALUES" + "(null, '"+nama+"','"+nik+"','"+alamat+"','"+telepon+"','"+email+"','"+nopol+"','"+tgll1+"','"+tgll2+"','"+harga+"', '"+durasi+"','"+total+"')";
                        stm = con.createStatement();
                        stm.executeUpdate(addTransaction);
                    }catch(SQLException e) {
                        
                    }
                }catch(SQLException e) {
                    JOptionPane.showMessageDialog(null, "Gagal");
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Gagal Menambah Data Peminjaman");
            }   
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void nopolCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolCmbActionPerformed
        tampil();
    }//GEN-LAST:event_nopolCmbActionPerformed

    private void tgl1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl1PropertyChange
        if(tgl1.getDate()!=null) {
            SimpleDateFormat sdf = new SimpleDateFormat ("dd MMMM yyyy"); 
            tanggal1 = sdf.format(tgl1.getDate());
        }
    }//GEN-LAST:event_tgl1PropertyChange

    private void tgl2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl2PropertyChange
        if(tgl2.getDate()!=null) {
            SimpleDateFormat sdf = new SimpleDateFormat ("dd MMMM yyyy"); 
            tanggal2 = sdf.format(tgl2.getDate());
        }
    }//GEN-LAST:event_tgl2PropertyChange

    private void hitungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBtnActionPerformed
        try {
            DateFormat format = new SimpleDateFormat("dd MMMM yyyy");
            Date pinjam = format.parse(tanggal1);
            Date kembali = format.parse(tanggal2);
            long pinjam1 = pinjam.getTime();
            long kembali1 = kembali.getTime();
            long diff = kembali1 - pinjam1;
            long durasi = diff / (24 * 60 * 60 * 1000);
            durasiField.setText(Long.toString(durasi) + "");
            long harga = Long.valueOf(priceField.getText());
            long total = durasi * harga;
            totalField.setText(Long.toString(total) + "");
            
        }catch(ParseException | NumberFormatException e) {
            
        }
        
    }//GEN-LAST:event_hitungBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        this.dispose();
        new rentcarView().setVisible(true);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void refreshBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_refreshBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rentcarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rentcarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rentcarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rentcarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new rentcarView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatField;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel durasiField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton hitungBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel merkField;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField nikField;
    private javax.swing.JComboBox nopolCmb;
    private javax.swing.JLabel priceField;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton refreshBtn1;
    private javax.swing.JLabel rpField;
    private javax.swing.JLabel statusField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTable table;
    private javax.swing.JLabel tahunField;
    private javax.swing.JTextField teleponField;
    private com.toedter.calendar.JDateChooser tgl1;
    private com.toedter.calendar.JDateChooser tgl2;
    private javax.swing.JLabel totalField;
    private javax.swing.JLabel typeField;
    // End of variables declaration//GEN-END:variables
}
