/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rental;

import Connection.koneksilogin;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AL-HACK3R
 */
public class transactionRent extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    DefaultTableModel tabModel;
    /**
     * Creates new form transactionRent
     */
    public transactionRent() {
        initComponents();
        tampil_data();
        peminjam();
        transaksi();
    }
    
    private void tampil_data() {
        Object baris[] = {"Id", "Nama", "NIK", "Alamat", "No. Telpon", "Email"};
        tabModel = new DefaultTableModel(null, baris);
        table.setModel(tabModel);
        try {
            con = new koneksilogin().ConnectDB();
            String select = "select * from transaction";
            stm = con.createStatement();
            rs = stm.executeQuery(select);
            while(rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                String nik = rs.getString("nik");
                String alamat = rs.getString("alamat");
                String telpon = rs.getString("telpon");
                String email = rs.getString("email");
                String[] data = {id, nama, nik, alamat, telpon, email};
                tabModel.addRow(data);
            }
        }catch(SQLException e) {
            
        }
    }
    
    
    private void peminjam() {
        namaField.setText("");
        nikField.setText("");
        alamatField.setText("");
        telponField.setText("");
        emailField.setText("");
        
    }
    
    private void transaksi() {
        nama2Field.setText("");
        nopolField.setText("");
        tgl1.setText("");
        tgl2.setText("");
        durasiField.setText("");
        totalField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namaField = new javax.swing.JLabel();
        nikField = new javax.swing.JLabel();
        telponField = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamatField = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nama2Field = new javax.swing.JLabel();
        nopolField = new javax.swing.JLabel();
        tgl1 = new javax.swing.JLabel();
        tgl2 = new javax.swing.JLabel();
        durasiField = new javax.swing.JLabel();
        totalField = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        totalField1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("DATA RIWAYAT PEMINJAM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 146, 770, 550));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nama ");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("NIK");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("No. Telepon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("E-mail");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        namaField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        namaField.setText("jLabel9");
        getContentPane().add(namaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 330, -1));

        nikField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nikField.setText("jLabel10");
        getContentPane().add(nikField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 330, -1));

        telponField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        telponField.setText("jLabel12");
        getContentPane().add(telponField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 330, -1));

        emailField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailField.setText("jLabel13");
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 320, -1));

        alamatField.setEditable(false);
        alamatField.setColumns(20);
        alamatField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        alamatField.setRows(5);
        jScrollPane3.setViewportView(alamatField);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 230, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Nama");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("No. Polisi");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Tanggal Peminjaman");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Tanggal Pengembalian");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Durasi");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Total Harga");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, -1, -1));

        nama2Field.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nama2Field.setText("jLabel15");
        getContentPane().add(nama2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 250, -1));

        nopolField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nopolField.setText("jLabel16");
        getContentPane().add(nopolField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 250, -1));

        tgl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tgl1.setText("jLabel17");
        getContentPane().add(tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 260, -1));

        tgl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tgl2.setText("jLabel18");
        getContentPane().add(tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 250, -1));

        durasiField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        durasiField.setText("jLabel19");
        getContentPane().add(durasiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 260, -1));

        totalField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        totalField.setText("jLabel20");
        getContentPane().add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 250, -1));

        jLabel15.setBackground(new java.awt.Color(3, 58, 89));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DATA PEMINJAM");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 198, 82));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DATA TRANSAKSI");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        closeBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit.png"))); // NOI18N
        closeBtn.setText("   Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/riwayat transaksi.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        totalField1.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        totalField1.setText("jLabel20");
        getContentPane().add(totalField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 250, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Biru.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int sel = table.getSelectedRow();
        String id = tabModel.getValueAt(sel, 0).toString();
        int ID = Integer.parseInt(id);
        try {
            String click1 = "select * from transaction where id = '" +ID+ "'";
            rs = stm.executeQuery(click1);
            while(rs.next()) {
                String nama = rs.getString("nama");
                String nik = rs.getString("nik");
                String alamat = rs.getString("alamat");
                String telpon = rs.getString("telpon");
                String email = rs.getString("email");
                String nopol = rs.getString("nopol");
                String tgll1 = rs.getString("tgl_pinjaman");
                String tgll2 = rs.getString("tgl_kembali");
                String durasi = rs.getString("durasi")+" hari";
                String total = rs.getString("total")+" rupiah";
                
                namaField.setText(nama);
                nikField.setText(nik);
                alamatField.setText(alamat);
                telponField.setText(telpon);
                emailField.setText(email);
                nama2Field.setText(nama);
                nopolField.setText(nopol);
                tgl1.setText(tgll1);
                tgl2.setText(tgll2);
                durasiField.setText(durasi);
                totalField.setText(total);
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal");
        }
    }//GEN-LAST:event_tableMouseClicked

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transactionRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transactionRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transactionRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transactionRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transactionRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatField;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel durasiField;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nama2Field;
    private javax.swing.JLabel namaField;
    private javax.swing.JLabel nikField;
    private javax.swing.JLabel nopolField;
    private javax.swing.JTable table;
    private javax.swing.JLabel telponField;
    private javax.swing.JLabel tgl1;
    private javax.swing.JLabel tgl2;
    private javax.swing.JLabel totalField;
    private javax.swing.JLabel totalField1;
    // End of variables declaration//GEN-END:variables
}
