/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

/**
 *
 * @author AL-HACK3R
 */
import Connection.koneksilogin;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class backrentView extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    DefaultTableModel tabModel;
    String tanggal1, tanggal2;
    /**
     * Creates new form backrentView
     */
    public backrentView() {
        initComponents();
        setTitle("Form Pengembalian Mobil");
        tampil_combo();
        tampil_data();
        tgl1Field.setText("");
        tgl2Field.setText("");
        durasiField.setText("");
        namaField.setText("");
        priceField.setText("");
    }
    
    private void tampil_combo() {
        try {
            con = koneksilogin.ConnectDB();
            String status = "Tidak Tersedia";
            String nopo = "select nopol from addcar where status = '"+status+"'";
            stm = con.createStatement();
            rs = stm.executeQuery(nopo);
            while (rs.next()) {
                String nopol = rs.getString(1);
                nopolCmb.addItem(nopol);
            }
        } catch (SQLException e) {

        }

    }

    public void tampil() {
        try {
            con = koneksilogin.ConnectDB();
            String no = "select * from addrent where nopol = '" + nopolCmb.getSelectedItem() + "'";
            stm = con.createStatement();
            rs = stm.executeQuery(no);
            while (rs.next()) {
                String harga = rs.getString("harga");
                String nama = rs.getString("nama");
                String tgl1 = rs.getString("tgl_pinjam");
                String tgl2 = rs.getString("tgl_kembali");
                String durasi = rs.getString("durasi");
                priceField.setText(harga);
                namaField.setText(nama);
                tgl1Field.setText(tgl1);
                tgl2Field.setText(tgl2);
                durasiField.setText(durasi);
            }
        } catch (SQLException e) {

        }
    }
    
    private void clear() {
        nopolCmb.setSelectedIndex(0);
        priceField.setText("");
        namaField.setText("");
        tgl1Field.setText("");
        tgl2Field.setText("");
        durasiField.setText("");
    }

    private void tampil_data() {
        Object baris[] = {"Id","Nama Peminjam", "No. Polisi", "Tanggal Peminjaman", "Tanggal Pengembalian", "Harga Sewa", "Durasi", "Total Harga"};
        tabModel = new DefaultTableModel(null, baris);
        table.setModel(tabModel);
        String select = "select * from addrent";
        try {
            con = koneksilogin.ConnectDB();
            stm = con.createStatement();
            rs = stm.executeQuery(select);
            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                String nopol = rs.getString("nopol");
                String tgll1 = rs.getString("tgl_pinjam");
                String tgll2 = rs.getString("tgl_kembali");
                String harga = rs.getString("harga");
                String durasi = rs.getString("durasi");
                String total = rs.getString("total");
                String[] data = {id, nama, nopol, tgll1, tgll2, harga, durasi, total};
                tabModel.addRow(data);
            }
        } catch (SQLException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nopolCmb = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        freshBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        clearBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        namaField = new javax.swing.JLabel();
        priceField = new javax.swing.JLabel();
        tgl1Field = new javax.swing.JLabel();
        tgl2Field = new javax.swing.JLabel();
        durasiField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Nama ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("No. Polisi");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        nopolCmb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        nopolCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        nopolCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolCmbActionPerformed(evt);
            }
        });
        getContentPane().add(nopolCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 330, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setText("Harga Sewa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Tanggal Peminjaman");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Tanggal Pengembalian");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Lama peminjaman");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        back.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/return (1).png"))); // NOI18N
        back.setText(" RETURN CAR");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 250, -1));

        freshBtn.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        freshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh (1).png"))); // NOI18N
        freshBtn.setText(" REFRESH");
        freshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freshBtnActionPerformed(evt);
            }
        });
        getContentPane().add(freshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 250, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        table.setEnabled(false);
        jScrollPane5.setViewportView(table);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1301, 228));

        clearBtn.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh.png"))); // NOI18N
        clearBtn.setText(" CLEAR FORM");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 250, -1));

        closeBtn.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit.png"))); // NOI18N
        closeBtn.setText(" CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 250, -1));

        namaField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        namaField.setForeground(java.awt.Color.red);
        namaField.setText("jLabel1");
        getContentPane().add(namaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 330, -1));

        priceField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        priceField.setForeground(java.awt.Color.red);
        priceField.setText("jLabel1");
        getContentPane().add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 330, -1));

        tgl1Field.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tgl1Field.setForeground(java.awt.Color.red);
        tgl1Field.setText("jLabel1");
        getContentPane().add(tgl1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 180, -1));

        tgl2Field.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tgl2Field.setForeground(java.awt.Color.red);
        tgl2Field.setText("jLabel1");
        getContentPane().add(tgl2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 180, -1));

        durasiField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        durasiField.setForeground(java.awt.Color.red);
        durasiField.setText("jLabel1");
        getContentPane().add(durasiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 280, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 40, 64));
        jLabel1.setText("FORM PENGEMBALIAN MOBIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/return car.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nopolCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolCmbActionPerformed
        tampil();
    }//GEN-LAST:event_nopolCmbActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        String nopol = nopolCmb.getSelectedItem().toString();
        if(nopol.equals("Pilih")){
            clear();
            JOptionPane.showMessageDialog(null, "No.Polisi Belum Dipilih atau Tidak Ada Peminjaman");
        }else {
            int doHapus = JOptionPane.showConfirmDialog(null, (Object) "Yakin ingin menyelesaikan transaksi ini?", "Konfirmasi Pengembalian Mobil", 0);

        if (doHapus == 0) {
            try {
                con = new koneksilogin().ConnectDB();
                String returnCar = "delete from addrent WHERE nopol = '" + nopol + "'";
                stm = con.createStatement();
                stm.executeUpdate(returnCar);
                JOptionPane.showMessageDialog(null, "Berhasil Mengembalikan Mobil");
                tampil_data();
                try {
                    String status = "Tersedia";
                    String update = "update addcar set status = '"+status+"' where nopol = '"+nopolCmb.getSelectedItem().toString()+"'";
                    stm = con.createStatement();
                    stm.execute(update);
                    tampil_data();
                    clear();
                }catch(Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal");
                }
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal Mengembalikan Mobil");
            }
        }
        }
        
    }//GEN-LAST:event_backActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void freshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freshBtnActionPerformed
        this.dispose();
        new backrentView().setVisible(true);
    }//GEN-LAST:event_freshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(backrentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(backrentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(backrentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(backrentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new backrentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel durasiField;
    private javax.swing.JButton freshBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel namaField;
    private javax.swing.JComboBox nopolCmb;
    private javax.swing.JLabel priceField;
    private javax.swing.JTable table;
    private javax.swing.JLabel tgl1Field;
    private javax.swing.JLabel tgl2Field;
    // End of variables declaration//GEN-END:variables
}
