/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import Connection.koneksilogin;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author AL-HACK3R
 */
public class addStaff extends javax.swing.JFrame {
Connection con;
Statement stm;
ResultSet rs;
DefaultTableModel tabModel;
    /**
     * Creates new form addStaff
     */
    public addStaff() {
        initComponents();
        setTitle("Form Tambah User");
        tampil_data();
        editBtn.setVisible(false);
        hapusBtn.setVisible(false);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x,y);
    }
    
    private void clear() {
        namaField.setText("");
        usernameField.setText("");
        passwordField.setText("");
        editBtn.setVisible(false);
        hapusBtn.setVisible(false);
    }
    
    private void tampil_data() {
        Object baris[] = {"Id", "Nama", "Username", "Password"};
        tabModel = new DefaultTableModel(null, baris);
        table.setModel(tabModel);
        try {
            String role = "staff";
            con = new koneksilogin().ConnectDB();
            String select = "select * from login where roles = '"+role+"'";
            stm = con.createStatement();
            rs = stm.executeQuery(select);
            while(rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                String username = rs.getString("username");
                String password = rs.getString("password");
                String[] data = {id, nama, username, password};
                tabModel.addRow(data);
            }
        }catch(Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        hapusBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        closeBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        hapusBtn1.setText("HAPUS");
        hapusBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 47, 73));
        jLabel1.setText("TAMBAH USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 47, 75));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        jLabel2.setText("  USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 47, 75));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/lock.png"))); // NOI18N
        jLabel3.setText("  PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        usernameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, -1));

        passwordField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 190, -1));

        tambahBtn.setText("TAMBAH");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tambahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        editBtn.setText("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 70, -1));

        hapusBtn.setText("HAPUS");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hapusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 440, 122));

        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 60));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 47, 75));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        jLabel5.setText("  NAMA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        namaField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(namaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 190, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tambahstaff.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        editBtn.setVisible(true);
        hapusBtn.setVisible(true);
        int sel = table.getSelectedRow();
        String id = tabModel.getValueAt(sel, 0).toString();
        int ID = Integer.parseInt(id);
        try {
            String click = "select * from login where id = '" +ID+ "'";
            rs = stm.executeQuery(click);
            while(rs.next()) {
                String username = rs.getString("username");
                String password = rs.getString("password");
                String nama = rs.getString("nama");
                
                usernameField.setText(username);
                passwordField.setText(password);
                namaField.setText(nama);
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal");
        }
    }//GEN-LAST:event_tableMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        String nama = namaField.getText();
        String username = usernameField.getText();
        String password = passwordField.getText();
        int sel = table.getSelectedRow();
        String id = tabModel.getValueAt(sel, 0).toString();
        int ID = Integer.parseInt(id);
        if(nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Field Nama Belum Diisi");
        }
        if(username.equals("")) {
            JOptionPane.showMessageDialog(null, "Field Username Belum Diisi");
        }
        if(password.equals("")) {
            JOptionPane.showMessageDialog(null, "Field Password Belum Diisi");
        }
        if(!nama.equals("") && !username.equals("") && !password.equals("")) {
            try {
            con = new koneksilogin().ConnectDB();
            String editCar = "update login set nama = '"+nama+"', username = '"+username+"', password = '"+password+"' where id = '"+ID+"'";
            stm = con.createStatement();
            stm.executeUpdate(editCar);
            JOptionPane.showMessageDialog(null, "Berhasil Mengubah User");
            tampil_data();
            clear();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Gagal Mengubah User");
            }
        }        
    }//GEN-LAST:event_editBtnActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        String nama = namaField.getText();
        String username = usernameField.getText();
        String password = passwordField.getText();
        String roles = "staff";
        if(nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Field Nama Belum Diisi");
        }
        if(username.equals("")) {
            JOptionPane.showMessageDialog(null, "Field Username Belum Diisi");
        }
        if(password.equals("")) {
            JOptionPane.showMessageDialog(null, "Field Password Belum Diisi");
        }
        if(!nama.equals("") && !username.equals("") && !password.equals("")) {
            try {
            con = new koneksilogin().ConnectDB();
            String addUser = "INSERT INTO `login` (id, nama, username, password, roles) VALUES" + "(null, '"+nama+"','"+username+"','"+password+"','"+roles+"')";
            stm = con.createStatement();
            stm.executeUpdate(addUser);
            JOptionPane.showMessageDialog(null, "Berhasil Menambah User");
            tampil_data();
            clear();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Gagal Menambah User");
            }
        }       
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        int sel = table.getSelectedRow();
        String id = tabModel.getValueAt(sel, 0).toString();
        int ID = Integer.parseInt(id);        
        int doHapus = JOptionPane.showConfirmDialog(table, (Object) "Yakin ingin menghapus user ini?", "Hapus user", 0);

        if (doHapus == 0) {
            try {
                con = new koneksilogin().ConnectDB();
                String deleteUser = "delete from login WHERE id = '" + ID + "'";
                stm = con.createStatement();
                stm.executeUpdate(deleteUser);
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus User");
                tampil_data();
                clear();
            }catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void hapusBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusBtn1ActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton hapusBtn1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTable table;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
